/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui.sa.soilcorrection.view;

/**
 *
 * @author mvsro
 */
public class telaEquilibrioCorrecaoCTC extends javax.swing.JFrame {

    /**
     * Creates new form telaEquilibrioCorrecaoCTC
     */
    public telaEquilibrioCorrecaoCTC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_Produtor = new javax.swing.JTextField();
        txt_Município = new javax.swing.JTextField();
        txt_Talhao = new javax.swing.JTextField();
        txt_Textura_Solo = new javax.swing.JTextField();
        txt_Responsável_Tecnico = new javax.swing.JTextField();
        txt_Resultado_solos = new javax.swing.JTextField();
        txt_Lote = new javax.swing.JTextField();
        txt_Data = new javax.swing.JFormattedTextField();
        txt_Area_do_talhao = new javax.swing.JTextField();
        txt_Sistema_de_Cultivo = new javax.swing.JTextField();
        txt_Profundidade_solos = new javax.swing.JTextField();
        txt_Area_Total = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelArgiloso = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        txt_Resultado_solos1 = new javax.swing.JTextField();
        txt_Resultado_solos2 = new javax.swing.JTextField();
        txt_Resultado_solos3 = new javax.swing.JTextField();
        txt_Resultado_solos4 = new javax.swing.JTextField();
        txt_Resultado_solos5 = new javax.swing.JTextField();
        txt_Resultado_solos6 = new javax.swing.JTextField();
        txt_Resultado_solos7 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txt_Resultado_solos8 = new javax.swing.JTextField();
        txt_Resultado_solos9 = new javax.swing.JTextField();
        txt_Resultado_solos10 = new javax.swing.JTextField();
        txt_Resultado_solos11 = new javax.swing.JTextField();
        txt_Resultado_solos12 = new javax.swing.JTextField();
        txt_Resultado_solos13 = new javax.swing.JTextField();
        txt_Resultado_solos14 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txt_Resultado_solos15 = new javax.swing.JTextField();
        txt_Resultado_solos16 = new javax.swing.JTextField();
        txt_Resultado_solos17 = new javax.swing.JTextField();
        txt_Resultado_solos18 = new javax.swing.JTextField();
        txt_Resultado_solos19 = new javax.swing.JTextField();
        txt_Resultado_solos20 = new javax.swing.JTextField();
        txt_Resultado_solos21 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txt_Resultado_solos22 = new javax.swing.JTextField();
        txt_Resultado_solos23 = new javax.swing.JTextField();
        txt_Resultado_solos24 = new javax.swing.JTextField();
        txt_Resultado_solos29 = new javax.swing.JTextField();
        txt_Resultado_solos30 = new javax.swing.JTextField();
        txt_Resultado_solos31 = new javax.swing.JTextField();
        txt_Resultado_solos32 = new javax.swing.JTextField();
        txt_Resultado_solos33 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txt_Resultado_solos34 = new javax.swing.JTextField();
        txt_Resultado_solos36 = new javax.swing.JTextField();
        txt_Resultado_solos38 = new javax.swing.JTextField();
        lblTipoVal = new javax.swing.JLabel();
        lblTipoVal2 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txt_Resultado_solos35 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Produtor:");

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel3.setText("Município:");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel4.setText("Talhão:");

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel5.setText("Textura Solo:");

        jLabel6.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel6.setText("Responsável Técnico:");

        jLabel7.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel7.setText("Resultado da análise de solos N°:");

        jLabel8.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel8.setText("Data:");

        jLabel9.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel9.setText("Lote:");

        jLabel10.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel10.setText("Área do talhão (ha):");

        jLabel11.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel11.setText("Sistema de Cultivo:");

        jLabel12.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel12.setText("Profundidade da amostra de solos:");

        jLabel13.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel13.setText("Área Total (ha):");

        txt_Resultado_solos.setEditable(false);
        txt_Resultado_solos.setBackground(new java.awt.Color(255, 255, 255));
        txt_Resultado_solos.setForeground(new java.awt.Color(21, 6, 255));
        txt_Resultado_solos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos.setText("9,0");
        txt_Resultado_solos.setCaretColor(new java.awt.Color(21, 6, 255));

        txt_Data.setText("01/01/2021");
        txt_Data.setToolTipText("01/01/2021");
        txt_Data.setActionCommand("<Not Set>");

        jLabel16.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel16.setText("Argiloso:");

        jLabel15.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel15.setText("Plantio Direto");

        labelArgiloso.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelArgiloso.setForeground(new java.awt.Color(74, 48, 255));
        labelArgiloso.setText("+ 40 de argila");
        labelArgiloso.setToolTipText("");

        jPanel5.setBackground(new java.awt.Color(255, 255, 0));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));

        jLabel14.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel14.setText("mg.dm3");

        jLabel17.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel17.setText("Enxofre");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator10)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(40, 255, 79));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jLabel18.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel18.setText("cmol");

        jLabel19.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel19.setText("Potássio");

        jLabel20.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel20.setText("Cálcio");

        jLabel21.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel21.setText("Magnésio");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel18)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(31, 31, 31)
                .addComponent(jLabel21)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel6.setBackground(new java.awt.Color(0, 202, 252));

        jLabel22.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel22.setText("Alumínio");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel23.setText("Teores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel23)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(31, 31, 31))
        );

        jPanel7.setBackground(new java.awt.Color(124, 170, 252));

        jLabel24.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel24.setText("H + AL");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel24)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        jLabel25.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel25.setText("mg.dm3");

        jLabel26.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel26.setText("mehlich");

        jLabel27.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel27.setText("Fósforo");

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel27)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addGap(47, 47, 47))
        );

        jLabel28.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel28.setText("No solo:");

        txt_Resultado_solos2.setBackground(new java.awt.Color(220, 220, 220));

        txt_Resultado_solos3.setBackground(new java.awt.Color(220, 220, 220));

        txt_Resultado_solos4.setBackground(new java.awt.Color(220, 220, 220));

        txt_Resultado_solos5.setBackground(new java.awt.Color(220, 220, 220));

        txt_Resultado_solos6.setBackground(new java.awt.Color(220, 220, 220));

        txt_Resultado_solos7.setBackground(new java.awt.Color(220, 220, 220));

        jLabel29.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel29.setText("Ideal:");

        txt_Resultado_solos8.setBackground(new java.awt.Color(220, 220, 220));

        txt_Resultado_solos9.setEditable(false);
        txt_Resultado_solos9.setBackground(new java.awt.Color(255, 255, 255));
        txt_Resultado_solos9.setForeground(new java.awt.Color(21, 6, 255));
        txt_Resultado_solos9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos9.setText("0,35");
        txt_Resultado_solos9.setCaretColor(new java.awt.Color(21, 6, 255));

        txt_Resultado_solos10.setEditable(false);
        txt_Resultado_solos10.setBackground(new java.awt.Color(255, 255, 255));
        txt_Resultado_solos10.setForeground(new java.awt.Color(21, 6, 255));
        txt_Resultado_solos10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos10.setText("6,0");
        txt_Resultado_solos10.setCaretColor(new java.awt.Color(21, 6, 255));
        txt_Resultado_solos10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Resultado_solos10ActionPerformed(evt);
            }
        });

        txt_Resultado_solos11.setEditable(false);
        txt_Resultado_solos11.setBackground(new java.awt.Color(255, 255, 255));
        txt_Resultado_solos11.setForeground(new java.awt.Color(21, 6, 255));
        txt_Resultado_solos11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos11.setText("1,5");
        txt_Resultado_solos11.setCaretColor(new java.awt.Color(21, 6, 255));

        txt_Resultado_solos12.setEditable(false);
        txt_Resultado_solos12.setBackground(new java.awt.Color(255, 255, 255));
        txt_Resultado_solos12.setForeground(new java.awt.Color(21, 6, 255));
        txt_Resultado_solos12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos12.setText("9,0");
        txt_Resultado_solos12.setCaretColor(new java.awt.Color(21, 6, 255));

        txt_Resultado_solos13.setEditable(false);
        txt_Resultado_solos13.setBackground(new java.awt.Color(255, 255, 255));
        txt_Resultado_solos13.setForeground(new java.awt.Color(21, 6, 255));
        txt_Resultado_solos13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos13.setText("0,0");
        txt_Resultado_solos13.setCaretColor(new java.awt.Color(21, 6, 255));

        txt_Resultado_solos14.setEditable(false);
        txt_Resultado_solos14.setBackground(new java.awt.Color(255, 255, 255));
        txt_Resultado_solos14.setForeground(new java.awt.Color(21, 6, 255));
        txt_Resultado_solos14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos14.setCaretColor(new java.awt.Color(21, 6, 255));

        jLabel30.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel30.setText("Após Correção:");

        txt_Resultado_solos15.setEditable(false);
        txt_Resultado_solos15.setBackground(new java.awt.Color(49, 88, 80));
        txt_Resultado_solos15.setForeground(new java.awt.Color(255, 255, 255));
        txt_Resultado_solos15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos15.setCaretColor(new java.awt.Color(21, 6, 255));

        txt_Resultado_solos16.setEditable(false);
        txt_Resultado_solos16.setBackground(new java.awt.Color(49, 88, 80));
        txt_Resultado_solos16.setForeground(new java.awt.Color(255, 255, 255));
        txt_Resultado_solos16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos16.setText("0,15");
        txt_Resultado_solos16.setCaretColor(new java.awt.Color(21, 6, 255));

        txt_Resultado_solos17.setEditable(false);
        txt_Resultado_solos17.setBackground(new java.awt.Color(49, 88, 80));
        txt_Resultado_solos17.setForeground(new java.awt.Color(255, 255, 255));
        txt_Resultado_solos17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos17.setCaretColor(new java.awt.Color(21, 6, 255));
        txt_Resultado_solos17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Resultado_solos17ActionPerformed(evt);
            }
        });

        txt_Resultado_solos18.setEditable(false);
        txt_Resultado_solos18.setBackground(new java.awt.Color(49, 88, 80));
        txt_Resultado_solos18.setForeground(new java.awt.Color(255, 255, 255));
        txt_Resultado_solos18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos18.setText("1,63");
        txt_Resultado_solos18.setCaretColor(new java.awt.Color(21, 6, 255));

        txt_Resultado_solos19.setEditable(false);
        txt_Resultado_solos19.setBackground(new java.awt.Color(255, 255, 255));
        txt_Resultado_solos19.setForeground(new java.awt.Color(21, 6, 255));
        txt_Resultado_solos19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos19.setCaretColor(new java.awt.Color(21, 6, 255));

        txt_Resultado_solos20.setEditable(false);
        txt_Resultado_solos20.setBackground(new java.awt.Color(255, 255, 255));
        txt_Resultado_solos20.setForeground(new java.awt.Color(21, 6, 255));
        txt_Resultado_solos20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos20.setCaretColor(new java.awt.Color(21, 6, 255));

        txt_Resultado_solos21.setEditable(false);
        txt_Resultado_solos21.setBackground(new java.awt.Color(255, 255, 255));
        txt_Resultado_solos21.setForeground(new java.awt.Color(21, 6, 255));
        txt_Resultado_solos21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos21.setCaretColor(new java.awt.Color(21, 6, 255));

        jLabel31.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel31.setText("S cmol:");

        jLabel32.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel32.setText("CTC cmol :");

        jLabel33.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel33.setText("V%  atual:");

        txt_Resultado_solos22.setEditable(false);
        txt_Resultado_solos22.setBackground(new java.awt.Color(245, 235, 131));
        txt_Resultado_solos22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos22.setText("7,54");
        txt_Resultado_solos22.setCaretColor(new java.awt.Color(21, 6, 255));

        txt_Resultado_solos23.setBackground(new java.awt.Color(245, 235, 131));
        txt_Resultado_solos23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos23.setText("12,89");
        txt_Resultado_solos23.setCaretColor(new java.awt.Color(21, 6, 255));

        txt_Resultado_solos24.setEditable(false);
        txt_Resultado_solos24.setBackground(new java.awt.Color(245, 235, 131));
        txt_Resultado_solos24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos24.setText("58,49");
        txt_Resultado_solos24.setCaretColor(new java.awt.Color(21, 6, 255));

        txt_Resultado_solos29.setBackground(new java.awt.Color(220, 220, 220));

        txt_Resultado_solos30.setBackground(new java.awt.Color(220, 220, 220));

        txt_Resultado_solos31.setBackground(new java.awt.Color(220, 220, 220));

        txt_Resultado_solos32.setBackground(new java.awt.Color(220, 220, 220));

        txt_Resultado_solos33.setBackground(new java.awt.Color(220, 220, 220));

        jLabel34.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel34.setText("M.O. (g.dm3)");

        txt_Resultado_solos34.setEditable(false);
        txt_Resultado_solos34.setBackground(new java.awt.Color(255, 255, 255));

        txt_Resultado_solos36.setEditable(false);
        txt_Resultado_solos36.setBackground(new java.awt.Color(255, 255, 255));

        txt_Resultado_solos38.setEditable(false);
        txt_Resultado_solos38.setBackground(new java.awt.Color(255, 255, 255));

        lblTipoVal.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lblTipoVal.setText("M.O. %");

        lblTipoVal2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lblTipoVal2.setText("Carbono");

        jLabel39.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel39.setText("Teor ideal de M.O.:");

        txt_Resultado_solos35.setEditable(false);
        txt_Resultado_solos35.setBackground(new java.awt.Color(255, 204, 153));
        txt_Resultado_solos35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Resultado_solos35.setText("3,0 a 4,0%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Produtor))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Responsável_Tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Textura_Solo, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Talhao, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Resultado_solos1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_Município, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelArgiloso, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_Profundidade_solos))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_Sistema_de_Cultivo))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_Area_do_talhao))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_Lote))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_Area_Total))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(txt_Resultado_solos16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txt_Resultado_solos17, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Resultado_solos18, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Resultado_solos19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Resultado_solos20, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Resultado_solos21, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel34)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_Resultado_solos22)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Resultado_solos23, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Resultado_solos24, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_Resultado_solos34, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addGap(46, 46, 46)
                                .addComponent(lblTipoVal)
                                .addGap(45, 45, 45)
                                .addComponent(txt_Resultado_solos36, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(lblTipoVal2)
                                .addGap(36, 36, 36)
                                .addComponent(txt_Resultado_solos38, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel39))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_Resultado_solos29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_Resultado_solos30, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(txt_Resultado_solos31, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_Resultado_solos32, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Resultado_solos33, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(txt_Resultado_solos35)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel30)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Resultado_solos15)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Resultado_solos)
                            .addComponent(txt_Resultado_solos8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txt_Resultado_solos9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_Resultado_solos10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txt_Resultado_solos2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_Resultado_solos3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Resultado_solos4)
                                    .addComponent(txt_Resultado_solos11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Resultado_solos5)
                            .addComponent(txt_Resultado_solos12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Resultado_solos6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Resultado_solos13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Resultado_solos7)
                            .addComponent(txt_Resultado_solos14, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(labelArgiloso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_Produtor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_Município, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_Talhao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_Textura_Solo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_Responsável_Tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_Resultado_solos1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_Lote, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_Area_do_talhao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_Sistema_de_Cultivo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_Profundidade_solos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txt_Area_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txt_Resultado_solos2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txt_Resultado_solos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txt_Resultado_solos15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Resultado_solos22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(txt_Resultado_solos23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Resultado_solos29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Resultado_solos34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos36, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultado_solos38, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoVal)
                    .addComponent(lblTipoVal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txt_Resultado_solos35, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Resultado_solos10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Resultado_solos10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Resultado_solos10ActionPerformed

    private void txt_Resultado_solos17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Resultado_solos17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Resultado_solos17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaEquilibrioCorrecaoCTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaEquilibrioCorrecaoCTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaEquilibrioCorrecaoCTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaEquilibrioCorrecaoCTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaEquilibrioCorrecaoCTC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel labelArgiloso;
    private javax.swing.JLabel lblTipoVal;
    private javax.swing.JLabel lblTipoVal2;
    private javax.swing.JTextField txt_Area_Total;
    private javax.swing.JTextField txt_Area_do_talhao;
    private javax.swing.JFormattedTextField txt_Data;
    private javax.swing.JTextField txt_Lote;
    private javax.swing.JTextField txt_Município;
    private javax.swing.JTextField txt_Produtor;
    private javax.swing.JTextField txt_Profundidade_solos;
    private javax.swing.JTextField txt_Responsável_Tecnico;
    private javax.swing.JTextField txt_Resultado_solos;
    private javax.swing.JTextField txt_Resultado_solos1;
    private javax.swing.JTextField txt_Resultado_solos10;
    private javax.swing.JTextField txt_Resultado_solos11;
    private javax.swing.JTextField txt_Resultado_solos12;
    private javax.swing.JTextField txt_Resultado_solos13;
    private javax.swing.JTextField txt_Resultado_solos14;
    private javax.swing.JTextField txt_Resultado_solos15;
    private javax.swing.JTextField txt_Resultado_solos16;
    private javax.swing.JTextField txt_Resultado_solos17;
    private javax.swing.JTextField txt_Resultado_solos18;
    private javax.swing.JTextField txt_Resultado_solos19;
    private javax.swing.JTextField txt_Resultado_solos2;
    private javax.swing.JTextField txt_Resultado_solos20;
    private javax.swing.JTextField txt_Resultado_solos21;
    private javax.swing.JTextField txt_Resultado_solos22;
    private javax.swing.JTextField txt_Resultado_solos23;
    private javax.swing.JTextField txt_Resultado_solos24;
    private javax.swing.JTextField txt_Resultado_solos29;
    private javax.swing.JTextField txt_Resultado_solos3;
    private javax.swing.JTextField txt_Resultado_solos30;
    private javax.swing.JTextField txt_Resultado_solos31;
    private javax.swing.JTextField txt_Resultado_solos32;
    private javax.swing.JTextField txt_Resultado_solos33;
    private javax.swing.JTextField txt_Resultado_solos34;
    private javax.swing.JTextField txt_Resultado_solos35;
    private javax.swing.JTextField txt_Resultado_solos36;
    private javax.swing.JTextField txt_Resultado_solos38;
    private javax.swing.JTextField txt_Resultado_solos4;
    private javax.swing.JTextField txt_Resultado_solos5;
    private javax.swing.JTextField txt_Resultado_solos6;
    private javax.swing.JTextField txt_Resultado_solos7;
    private javax.swing.JTextField txt_Resultado_solos8;
    private javax.swing.JTextField txt_Resultado_solos9;
    private javax.swing.JTextField txt_Sistema_de_Cultivo;
    private javax.swing.JTextField txt_Talhao;
    private javax.swing.JTextField txt_Textura_Solo;
    // End of variables declaration//GEN-END:variables
}
